### ISSUE TITLE
Take advantage of Component in Paper 1.16.5+

### ISSUE THREAD

**Issue by HSGamer** [zivoric/ZEnchantmentCore#5]
Since `getLore` is deprecated in Paper and `lore` is now a `Component`, we can take advantage of it, particularly `TranslatableComponent`.
Maybe with an external handler so that we can switch between the current implementation and the new one.
You can check it here: https://github.com/HSGamer/PaperEnchantmentCore

#3 and this may requires the removal of `parseLore` in `EnchantmentUtils` and its related methods.

**Comment by zivoric** [comment]
I see you added the `LoreHandler` interface with the `DefaultLoreHandler` implementation. Was the idea that you would create another `LoreHandler` implementation for Paper? 
Also, for the Paper methods in `CustomEnch`, I removed them earlier because they didn't work when Paper wasn't installed. Maybe there is a way to reimplement the methods only for when Paper is installed. Will figure that out

**Comment by HSGamer** [comment]
> I see you added the `LoreHandler` interface with the `DefaultLoreHandler` implementation. Was the idea that you would create another `LoreHandler` implementation for Paper? 
> Also, for the Paper methods in `CustomEnch`, I removed them earlier because they didn't work when Paper wasn't installed. Maybe there is a way to reimplement the methods only for when Paper is installed. Will figure that out

There will be a check on the main plugin that check for Paper, then it'll set the lore handler to Paper-specific.

**Comment by HSGamer** [comment]
We can't add it in the main core.
However, #7 allows multiple lore handlers at the same time. The developers can do that on their own addons.

**Comment by zivoric** [comment]
> We can't add it in the main core.
> However, #7 allows multiple lore handlers at the same time. The developers can do that on their own addons.

Ideally, the plugin would be compatible with Paper and Spigot without the developers having to write for both individually. I'm gonna test a few things and will update this if I come up with anything to solve this

**Comment by zivoric** [comment]
I just added a few things that allow developers to take advantage of the Paper API (components, etc). I'm not closing this issue yet because there are probably ways it can be improved/changed

**Comment by zivoric** [comment]
This is basically done now, closing this issue
